---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Tuesday Agenda

- Welcome and [introductions](https://docs.google.com/document/d/1K4MdUToFKqQ2TmZB6JPlNt6_6Uj3CnTA70769J4tNVY/edit?usp=sharing)
- The [problem with p-values](presentations/problems-with-p-values.html)
- Where statistics and data science fail to connect.
- Other problems in Stat 101
    - discussion: What don't we like. [document](https://docs.google.com/document/d/1FCIgrFNXQ_q4p-WRXtLtNY1HdH5i24uQS9frDBc3z7g/edit?usp=sharing)
    - the problem with means [slides]()
        - Lesson: WHICH APP FOR MAKING  SUMMARY INTERVALS?
    - the problems with standard deviations (including defining interval length as average of point-to-point interval)
        - Using summary interval length instead.
- What do data scientists do?
    - prediction
    - causation 
    - exploration
- Computation: two paradigms
    - R
    - Little Apps
- Stats for data science
- A unifying paradigm: inference with model values

# Wednesday Agenda

- The problem with means
- Modeling at the core
- Effect sizes
- DAGs
- Bayes

# Thursday Agenda

What we'll do on Thursday




